---
engines:
  phan:
    enabled: true
    config:
      file_extensions: "php"
      dead-code-detection: true
      ignore-undeclared: true #sembra ci sia un bug relativo ai fullpath
      #minimum-severity: 10 #low=0, normal=5, critical=10 #altro bug confusione tra string e number
      backward-compatibility-checks: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: ruleset.xml
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
      ignore_warnings: true
      encoding: utf-8
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
- Command/
- Console/
- Tests/
- vendor/
