---
engines:
  phan:
    enabled: true
    config:
      file_extensions: "php"
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
- Tests/
- vendor/
