# curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@./composer.lock
# https://docs.travis-ci.com/user/languages/php
# https://docs.travis-ci.com/user/customizing-the-build

language: php

php:
  - '5.6'
  - '7.0'
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
      - php: hhvm

# env:
#   - SYMFONY_VERSION="3.0.*" DB=mysql
#   - DB=sqlite
#   - DB=mysql
#   - DB=postgres

# database
# https://docs.travis-ci.com/user/database-setup/

# services:
  #  - neo4j

sudo: false

# whitelist
branches:
  only:
    - master
    # - stable

# before_script:
  # - mkdir -p resources/logs resources/tmp

before_install:
  - composer --version

install:
  - composer install

cache:
  directories:
    - $HOME/.composer/cache/files

after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/test-reporter --stdout > codeclimate.json
  - 'curl -X POST -d @codeclimate.json -H "Content-Type: application/json" -H "User-Agent: Code Climate (PHP Test Reporter v1.0.1-dev)"  https://codeclimate.com/test_reports'
  #- cat app/logs/*

before_script:
  - mkdir -p build/logs

script:
#   - phpunit --configuration $DB.phpunit.xml
#   - phpunit --coverage-text
  - phpunit --process-isolation -c phpunit.xml.dist

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then travis_retry php ./vendor/bin/coveralls -v; fi;'
  - bash <(curl -s https://codecov.io/bash)

addons:
    code_climate:
        repo_token:
          # travis encrypt <token>
          secure: "gYSDGBvAHj5+T2XZ6CXnI/gsT5v1IEkimgANlg0jrg/IirOfbagbh2dwCdyTIhJUH2RbtElsuzN/a9KRgsSkFQbL2rTIpYQp/LOp8kic1ELp5fgwlylD96F9NpkpkV+aqY7c/GhoLdIUG3Bxe41hfnoLBE1EuMAt8mtjBgceShCnmfU3D9SOaPlFrOs29Pt4SCF1Se3ycL5ZTwJ+cD6o9WWCs5zAHigN+tXlU3C42PM8ihE802KXWQk2s8YkB1lP3O6FKlvBwZAFmWBAXqfuyoedS1N97hjOckqN9QYJk7AmGJHQKxPIu1AAuLpiTTQG4XpcRbH7o/14RmLYvIm1zNiICuWxNIClExFIaY7MDshZv5qnngKTEhajKp7cP4jMAwAhoIPFgBvh/6K03pOSeeRDFHYI8kU+virxSEticPK7SDZp5dT+9HYg8SWX2RFxugyN+aAD+NB76ow8cN2gdKU0MwqmrMqIaGaOqT4qmYRO5GccwxGrKbZThoZi+34+NXMzDoviMOMTu+NvSz2n7QXouRfhVgy+AU6YR3JRaezxnFfgIGrwnNLOc3XmHNnrNphHR3yVNbQvNOwJxgT/Tucv9lVFbunFoiuFb/z0uIYxSTdDhNXTSLjfOKOO+a8bRGw7fKrxCuJPi02t+0IjlU+iN7gWyyK0DXtOMQCeqn8="

# notifications:
#   slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
#   email:
#     - friendsofsymfony-dev@googlegroups.com
